export const SHOW_CAR_ELEMENT = "SHOW_CAR_ELEMENT";
export const CANCEL_CAR_ELEMENT_INFO = "CANCEL_CAR_ELEMENT_INFO";
export const SHOW_RENTAL_FORM = "SHOW_RENTAL_FORM";
export const SUBMIT_RENTAL_FORM = "SUBMIT_RENTAL_FORM";
export const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";
export const ONBLUR_EMAIL_VALIDATION = "ONBLUR_EMAIL_VALIDATION";
export const ONBLUR_PHONE_VALIDATION = "ONBLUR_PHONE_VALIDATION";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE"

export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_FAIL = "GET_REQUEST_FAIL";

export const POST_REQUEST = "POST_REQUEST";
export const POST_REQUEST_SUCCESS = "POST_REQUEST_SUCCESS";
export const POST_REQUEST_FAIL = "POST_REQUEST_FAIL";